// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn8dOi6gJOkaeiwuQiSwdOlbDdrpG1xYw',
    appId: '1:1011737977498:web:325e5a1cec2f0a82f03523',
    messagingSenderId: '1011737977498',
    projectId: 'mobilea3-75bcf',
    authDomain: 'mobilea3-75bcf.firebaseapp.com',
    storageBucket: 'mobilea3-75bcf.firebasestorage.app',
    measurementId: 'G-LVD11BYW53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYd5uNQ8UOOPCkkN7hSp2gtzG5-EVnpdE',
    appId: '1:1011737977498:android:b35f2ed05eb94af2f03523',
    messagingSenderId: '1011737977498',
    projectId: 'mobilea3-75bcf',
    storageBucket: 'mobilea3-75bcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh_pD5HCDpJ2FMBmh0DQNFgYf22c_y-9s',
    appId: '1:1011737977498:ios:34a2f03a6709521ef03523',
    messagingSenderId: '1011737977498',
    projectId: 'mobilea3-75bcf',
    storageBucket: 'mobilea3-75bcf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh_pD5HCDpJ2FMBmh0DQNFgYf22c_y-9s',
    appId: '1:1011737977498:ios:34a2f03a6709521ef03523',
    messagingSenderId: '1011737977498',
    projectId: 'mobilea3-75bcf',
    storageBucket: 'mobilea3-75bcf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn8dOi6gJOkaeiwuQiSwdOlbDdrpG1xYw',
    appId: '1:1011737977498:web:3a64544a21fc96c2f03523',
    messagingSenderId: '1011737977498',
    projectId: 'mobilea3-75bcf',
    authDomain: 'mobilea3-75bcf.firebaseapp.com',
    storageBucket: 'mobilea3-75bcf.firebasestorage.app',
    measurementId: 'G-H0E14WSR7N',
  );
}
